-- 创建员工列表表
CREATE TABLE IF NOT EXISTS employeelist (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  sex TINYINT NOT NULL COMMENT '0: 女, 1: 男',
  status TINYINT DEFAULT 1 COMMENT '1: 启用, 0: 禁用',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_name (name),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;